services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.dev
    container_name: frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    stdin_open: true
    tty: true
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./public
          target: /app/public
        - action: rebuild
          path: ./package.json

networks:
  app-network:
    external: true
    name: cloud-storage-app_app-network