"""criacao_tabela_file_audio

Revision ID: efc69596882d
Revises: e2f7be992db5
Create Date: 2025-07-06 03:44:50.218506+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc69596882d'
down_revision: Union[str, None] = 'e2f7be992db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_files',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='Identificador único do arquivo de áudio'),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False, comment='ID do usuário proprietário'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome do arquivo'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descrição do arquivo'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='Caminho do arquivo no sistema'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='Tipo MIME do arquivo'),
    sa.Column('extension', sa.String(length=10), nullable=False, comment='Extensão do arquivo'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='Categoria do arquivo (audio, image, video)'),
    sa.Column('size', sa.BigInteger(), nullable=False, comment='Tamanho do arquivo em bytes'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data de criação'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data da última atualização'),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True, comment='Data do último acesso'),
    sa.Column('tags', sa.Text(), nullable=True, comment='Tags do arquivo separadas por vírgulas'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='Duração do áudio em segundos'),
    sa.Column('bitrate', sa.Integer(), nullable=True, comment='Taxa de bits do áudio (kbps)'),
    sa.Column('sample_rate', sa.Integer(), nullable=True, comment='Taxa de amostragem (Hz)'),
    sa.Column('channels', sa.Integer(), nullable=True, comment='Número de canais de áudio'),
    sa.Column('genre', sa.String(length=100), nullable=True, comment='Gênero musical'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Indica se o arquivo foi deletado (soft delete)'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_files_owner_id'), 'audio_files', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_files_owner_id'), table_name='audio_files')
    op.drop_table('audio_files')
    # ### end Alembic commands ###