"""criacao_tabela_user

Revision ID: e2f7be992db5
Revises:
Create Date: 2025-06-07 02:17:35.119179+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f7be992db5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='Identificador único do usuário'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Nome de usuário único'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email único do usuário'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Senha hasheada do usuário'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Primeiro nome do usuário'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Sobrenome do usuário'),
    sa.Column('profile_picture', sa.String(length=500), nullable=True, comment='URL ou caminho da foto de perfil'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descrição/bio do usuário'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indica se o usuário está ativo'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data de criação'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data da última atualização'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Data do último login'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###