"""criacao_tabela_file_video

Revision ID: d10d0197cc3d
Revises: 67f5c2a3252e
Create Date: 2025-07-06 11:10:35.879530+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10d0197cc3d'
down_revision: Union[str, None] = '67f5c2a3252e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_files',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='Identificador único do arquivo de vídeo'),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False, comment='ID do usuário proprietário'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome do arquivo'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descrição do arquivo'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='Caminho do arquivo no sistema'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='Tipo MIME do arquivo'),
    sa.Column('extension', sa.String(length=10), nullable=False, comment='Extensão do arquivo'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='Categoria do arquivo (audio, image, video)'),
    sa.Column('size', sa.BigInteger(), nullable=False, comment='Tamanho do arquivo em bytes'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data de criação'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data da última atualização'),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True, comment='Data do último acesso'),
    sa.Column('tags', sa.Text(), nullable=True, comment='Tags do arquivo separadas por vírgulas'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='Duração do vídeo em segundos'),
    sa.Column('width', sa.Integer(), nullable=True, comment='Largura do vídeo em pixels'),
    sa.Column('height', sa.Integer(), nullable=True, comment='Altura do vídeo em pixels'),
    sa.Column('frame_rate', sa.Float(), nullable=True, comment='Taxa de quadros por segundo (fps)'),
    sa.Column('bitrate', sa.Integer(), nullable=True, comment='Taxa de bits em kbps'),
    sa.Column('codec', sa.String(length=50), nullable=True, comment='Codec de vídeo utilizado'),
    sa.Column('audio_codec', sa.String(length=50), nullable=True, comment='Codec de áudio utilizado'),
    sa.Column('has_audio', sa.Boolean(), nullable=True, comment='Indica se o vídeo possui áudio'),
    sa.Column('has_subtitles', sa.Boolean(), nullable=True, comment='Indica se o vídeo possui legendas'),
    sa.Column('created_with', sa.String(length=100), nullable=True, comment='Software usado para criar o vídeo'),
    sa.Column('genre', sa.String(length=50), nullable=True, comment='Gênero do vídeo'),
    sa.Column('thumbnail', sa.String(length=500), nullable=True, comment='Caminho do thumbnail do vídeo'),
    sa.Column('versions', sa.JSON(), nullable=True, comment='Versões do vídeo em diferentes resoluções'),
    sa.Column('original_version', sa.String(length=20), nullable=True, comment='Resolução da versão original'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Indica se o arquivo foi deletado (soft delete)'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_files_owner_id'), 'video_files', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_files_owner_id'), table_name='video_files')
    op.drop_table('video_files')
    # ### end Alembic commands ###