"""criacao_tabela_file_image

Revision ID: 67f5c2a3252e
Revises: efc69596882d
Create Date: 2025-07-06 10:31:39.396089+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f5c2a3252e'
down_revision: Union[str, None] = 'efc69596882d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_files',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='Identificador único do arquivo de imagem'),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False, comment='ID do usuário proprietário'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome do arquivo'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descrição do arquivo'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='Caminho do arquivo no sistema'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='Tipo MIME do arquivo'),
    sa.Column('extension', sa.String(length=10), nullable=False, comment='Extensão do arquivo'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='Categoria do arquivo (audio, image, video)'),
    sa.Column('size', sa.BigInteger(), nullable=False, comment='Tamanho do arquivo em bytes'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data de criação'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data da última atualização'),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True, comment='Data do último acesso'),
    sa.Column('tags', sa.Text(), nullable=True, comment='Tags do arquivo separadas por vírgulas'),
    sa.Column('width', sa.Integer(), nullable=True, comment='Largura da imagem em pixels'),
    sa.Column('height', sa.Integer(), nullable=True, comment='Altura da imagem em pixels'),
    sa.Column('color_depth', sa.Integer(), nullable=True, comment='Profundidade de cor (bits por pixel)'),
    sa.Column('dpi', sa.Integer(), nullable=True, comment='Resolução em DPI'),
    sa.Column('has_transparency', sa.Boolean(), nullable=True, comment='Indica se a imagem possui transparência'),
    sa.Column('compression', sa.String(length=50), nullable=True, comment='Tipo de compressão da imagem'),
    sa.Column('camera_make', sa.String(length=100), nullable=True, comment='Fabricante da câmera'),
    sa.Column('camera_model', sa.String(length=100), nullable=True, comment='Modelo da câmera'),
    sa.Column('taken_at', sa.String(length=50), nullable=True, comment='Data/hora da foto em formato ISO'),
    sa.Column('gps_latitude', sa.Float(), nullable=True, comment='Latitude GPS'),
    sa.Column('gps_longitude', sa.Float(), nullable=True, comment='Longitude GPS'),
    sa.Column('thumbnail', sa.String(length=500), nullable=True, comment='Caminho do thumbnail da imagem'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Indica se o arquivo foi deletado (soft delete)'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_files_owner_id'), 'image_files', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_files_owner_id'), table_name='image_files')
    op.drop_table('image_files')
    # ### end Alembic commands ###