FROM python:3.12.3-slim

WORKDIR /app
ENV UV_PROJECT_ENVIRONMENT="/usr/local/"
ENV UV_COMPILE_BYTECODE=1

COPY pyproject.toml .
COPY uv.lock .

RUN pip install --no-cache-dir uv
RUN uv sync --frozen --group dev

# Configuração para ambiente de desenvolvimento
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY src/cloud-storage-app/ ./cloud-storage-app/

# Instalando dependências do servidor
RUN pip install "uvicorn[standard]" gunicorn

EXPOSE 8080

# Modo de recarregamento ativado por padrão para desenvolvimento
CMD ["uvicorn", "cloud-storage-app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"] 