FROM python:3.12.3-slim

WORKDIR /app
ENV UV_PROJECT_ENVIRONMENT="/usr/local/"
ENV UV_COMPILE_BYTECODE=1

# Instalar netcat para verificação do banco de dados
RUN apt-get update && apt-get install -y netcat-traditional && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml .
COPY uv.lock .

RUN pip install --no-cache-dir uv
RUN uv sync --frozen --group dev

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

COPY src/ ./
COPY alembic.ini .
COPY alembic ./alembic
COPY scripts ./scripts
COPY Dockerfiles/entrypoint.sh .

# Tornar o script de entrypoint executável
RUN chmod +x entrypoint.sh

EXPOSE 8080

# Usar o script de entrypoint
CMD ["./entrypoint.sh"]